### ISSUE TITLE
Syntax of headings - more than 1 star causes first star to use different color

### ISSUE THREAD

**Issue by ukdor** [melioratus/org-mode#10]
As I've been using org-mode grammar within Atom, I've found that the treatment of headings with more than 1 star seems odd, but maybe org-mode standard or by design.

IE:
Org-mode Syntax - only the last star follows text color:
![image](https://user-images.githubusercontent.com/34755921/37741643-d88d3d96-2d27-11e8-9fc0-eba5213f078f.png)

GitHub Markdown - headings with 2 or more stars, all stars follow text color:
![image](https://user-images.githubusercontent.com/34755921/37741632-ce7b329a-2d27-11e8-97fb-7b1238df234d.png)

**Comment by melioratus** [comment]
@ukdor 

Thanks for bringing the issue about using inconsistent styles in the headings to my attention.

This styling would be more at home in org-mode theme instead of the base package so I am going to remove it from Atom org-mode in the next release.

For those users that would like to keep the current look, please add the code below to your personal `style.less` under the `.atom` directory.

```less
.syntax--leading-star.syntax--org-mode  {
  color: @syntax-invisible-character-color;
  &:hover {
    color: multiply(@syntax-invisible-character-color, @syntax-invisible-character-color);
  }
}
```

Thanks for Help!

Brian K ~ @melioratus
